### 1. Criar explorador
POST http://localhost:5259/exploradores
Content-Type: application/json

{
    "Nome": "Xis"
}

### 2. Criar sistema (ganha 3 pontos)
POST http://localhost:5259/sistemas
Content-Type: application/json

{
    "Nome": "Alpha System",
    "ExploradorId": 1,
    "qntdPlanetas": 3
}

### 3. Criar planeta (5 base + qualidades)
POST http://localhost:5259/planetas
Content-Type: application/json

{
    "Nome": "Paradise World",
    "SistemaEstelarId": 1,
    "ExploradorId": 1,
    "Clima": "Tropical",
    "ClimaQualidade": "bom",
    "Fauna": "Rica",
    "FaunaQualidade": "bom",
    "Flora": "Abundante",
    "FloraQualidade": "bom",
    "Sentinelas": "Ausentes",
    "SentinelasQualidade": "bom",
    "Recursos": "Ouro, Diamante"
}

### 4. Ver leaderboard
GET http://localhost:5259/exploradores/leaderboard