// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NMS_Proj.Models;

#nullable disable

namespace NMS_Proj.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251008233046_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NMS_Proj.Models.Explorador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Exploradores");
                });

            modelBuilder.Entity("NMS_Proj.Models.Planeta", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClimaQualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExploradorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fauna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaunaQualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Flora")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FloraQualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeQualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recursos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sentinelas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentinelasQualidade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SistemaEstelarId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Nome");

                    b.HasIndex("ExploradorId");

                    b.HasIndex("SistemaEstelarId");

                    b.ToTable("Planetas");
                });

            modelBuilder.Entity("NMS_Proj.Models.SistemaEstelar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExploradorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("qntdPlanetas")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExploradorId");

                    b.ToTable("Sistemas");
                });

            modelBuilder.Entity("NMS_Proj.Models.Planeta", b =>
                {
                    b.HasOne("NMS_Proj.Models.Explorador", "Explorador")
                        .WithMany("PlanetasExplorados")
                        .HasForeignKey("ExploradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NMS_Proj.Models.SistemaEstelar", "SistemaEstelar")
                        .WithMany("Planetas")
                        .HasForeignKey("SistemaEstelarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Explorador");

                    b.Navigation("SistemaEstelar");
                });

            modelBuilder.Entity("NMS_Proj.Models.SistemaEstelar", b =>
                {
                    b.HasOne("NMS_Proj.Models.Explorador", "Explorador")
                        .WithMany("SistemasEstelares")
                        .HasForeignKey("ExploradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Explorador");
                });

            modelBuilder.Entity("NMS_Proj.Models.Explorador", b =>
                {
                    b.Navigation("PlanetasExplorados");

                    b.Navigation("SistemasEstelares");
                });

            modelBuilder.Entity("NMS_Proj.Models.SistemaEstelar", b =>
                {
                    b.Navigation("Planetas");
                });
#pragma warning restore 612, 618
        }
    }
}
